version: '3.4'

services:

  server:
    image: edittapi
    container_name: "edittapi"
    environment:
      - ACCESS_KEY=qwe
      - SECRET_KEY=qwe
    build: ./
    command: ./app
    ports:
      - 8000:8000
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:latest
    container_name: "localstack"
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'